name: Release

on:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - dev
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-22.04
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      # WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      # GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: Package and release
        uses: BigWigsMods/packager@master
